"""Users Rooms Bookings models add

Revision ID: 6463676c59b1
Revises: 6a4b8f112776
Create Date: 2025-01-29 13:53:59.487379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6463676c59b1'
down_revision: Union[str, None] = '6a4b8f112776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
